### ISSUE TITLE
Unable to use parallelism

### ISSUE THREAD

**Issue by ravipatel4** [Taiji-pipeline/Taiji#1]
Hello,
It looks like the pipeline is unable to use the workflow-level parallelism. I am using the following command to run the pipeline on ~50 ATAC- and RNA-Seq samples using a 32 cores / 128 GB RAM server. 
` taiji-Linux-x86_64 run --config config.yml -N 16
`
However, the pipeline uses a single core. Is it possible to use multiple cores for the processor-intensive jobs, like TFBS finding in open chromatin using FIMO, so that the analysis can be performed in shorter amount of time? I am using the latest release (v 0.5.0) of the pipeline.

Thank you for your help.

**Comment by kaizhang** [comment]
Please wait 1~2 weeks for the v1.0 beta release. This issue will be fixed in the new release.

**Comment by kaizhang** [comment]
The beta version is released! https://github.com/Taiji-pipeline/Taiji/releases/tag/1.0.0.21
To use multiple cores (5 cores for example), add `-n 5 +RTS -N5` to the end. Here is a tutorial in progress: https://taiji-pipeline.github.io/blog_ATAC-seq_walkthrough.html
