### ISSUE TITLE
Pipeline fails at Compute/Output ranks

### ISSUE THREAD

**Issue by clip78** [Taiji-pipeline/Taiji#10]
I ran the pipeline with ATAC-seq (bam files) and RNA-seq data (genequant). My input and config files are attached.

config.yml
`input: "input.tsv"
output_dir: "output/"
assembly: "mm10"`

input.tsv

![input](https://user-images.githubusercontent.com/10077337/89443392-38ca6380-d71e-11ea-9260-6ace4689701b.jpg)

`[ERROR][08-05 13:04] Output_Ranks(5095..) Failed: Prelude.maximum: empty list
CallStack (from HasCallStack):
  error, called at src/Control/Workflow/Interpreter/Exec.hs:145:37 in SciFlow-0.7.2-Jc8TJcu7aUL61DWlZpDMFY:Control.Workflow.Interpreter.Exec
[ERROR][08-05 13:04] Program exits with errors`

It seems to compute ranks for my first group of samples WT_E11.5, but not for WT_E14.5 or WT_E17.5:
`taiji show Compute_Ranks | head`
`<< Compute_Ranks(4bfa..) >>
( "WT_E11.5"
, [ ( "AC168977.1" , ( 1.7792576080965692e-4 , 0.0 ) )
  , ( "BCL6" , ( 2.6918930886374614e-3 , 0.0 ) )
  , ( "BCL6B" , ( 2.2402129605582377e-4 , 0.0 ) )
  , ( "CTCF" , ( 3.184018159520011e-2 , 0.0 ) )
  , ( "EGR1" , ( 3.6094455370085303e-3 , 0.0 ) )
  , ( "EHF" , ( 4.884570371492883e-4 , 0.0 ) )
  , ( "ELF1" , ( 1.231657411479836e-3 , 0.0 ) )
  , ( "ELF2" , ( 3.32650307749173e-3 , 0.0 ) )`

taiji show Output_Ranks has no output.

Any help is greatly appreciated.

**Comment by kaizhang** [comment]
The program failed to generate the HTML visualization probably because no gene passed the default filter. But the result ("GeneRanks.tsv") should be saved to the output directory. Despite the error message, you should have got everything you need.

**Comment by clip78** [comment]
OK, I see that. Thanks for your help!
