### ISSUE TITLE
RNA_Make_Index and SCATAC_Merged_Make_KNN Errors

### ISSUE THREAD

**Issue by phoebe460** [Taiji-pipeline/Taiji#14]
Hello Taiji Developers,

Happy new year! First off, thank you for making this awesome tool. So this is my first time trying out your tool, and I've run into some unusual errors. See below:

<img width="842" alt="Taiji Error" src="https://user-images.githubusercontent.com/56165012/103618398-c2a47580-4ee4-11eb-9803-c3131c94dc5d.png">

For what I used to run my program, I've made my input file with only quantification expression profiles, since I aligned my RNA-seq reads a different way and .bed files since I also aligned my ATAC-seq reads differently as well. For my configuration file, I provided my own index since I aligned my RNA-seq reads to a human GRCh38 transcriptome under "index" and also provided the actual transcriptome file I used in FASTA format (.fa) under "genome". Everything else in the configuration file, I kept commented and left the minimal settings section similar to what was given in the example config file.  

Do you know any reason why I am getting the RNA_Make_Index and SCATAC_Merged_Make_KNN errors? If you can help me out, then that I would greatly appreciate it!

Thank you!
Phoebe

P.S. If you need to see my configuration and input files, I have attached them as well. 

[config_PV.txt](https://github.com/Taiji-pipeline/Taiji/files/5768726/config_PV.txt)
[input_PV.txt](https://github.com/Taiji-pipeline/Taiji/files/5768727/input_PV.txt)

**Comment by kaizhang** [comment]
@phoebe460 Since you are using distributed computing, you need to set the parameters for workload manager properly, for example:

```
submit_params: "-p glean"
submit_command: "sbatch"
submit_cpu_format: "--ntasks-per-node=%d"
submit_memory_format: "--mem=%d000"
```

Please modify this accordingly.

**Comment by phoebe460** [comment]
Ok, thank you for your suggestion. So I have this in my configuration file. Is this correct? 

<img width="667" alt="Screen Shot 2021-01-05 at 11 31 48 AM" src="https://user-images.githubusercontent.com/56165012/103690467-a1c23b80-4f49-11eb-97fb-8ba84ccaaa80.png">
