### ISSUE TITLE
SwissRegulon Motif File Issue

### ISSUE THREAD

**Issue by phoebe460** [Taiji-pipeline/Taiji#17]
Hi Kai,

So I've been having this issue with reading in my motif file in .meme format generated from the SwissRegulon Motif database. I am not sure where I am getting the ```"Failed: Unexpected Line"``` error from? I look through my .meme file and I don't see any ```"UBL5, 0.1732050807568773 COMBINED_REGULATE"```.

<img width="995" alt="Taji_SR Error" src="https://user-images.githubusercontent.com/56165012/104483686-401f5400-557d-11eb-9032-ae82558b2e5a.png">

I've attached my .meme file below. Is there anyway to resolve this? Any help would be much appreciated again. 

Thank you!
Phoebe

[SwissRegulon_human_and_mouse.txt](https://github.com/Taiji-pipeline/Taiji/files/5810036/SwissRegulon_human_and_mouse.txt)

**Comment by kaizhang** [comment]
You need format the TF names: https://taiji-pipeline.github.io/documentation/options.html#motif-file

**Comment by phoebe460** [comment]
Sorry I haven't closed this issue yet. So I think I've decided not to use SwissRegulon motif file anymore with Taiji, but if I come across any other issues, will certainly let you know. Thanks again for all your help @kaizhang!
