### ISSUE TITLE
Documentation for scATAC analysis

### ISSUE THREAD

**Issue by ravipatel4** [Taiji-pipeline/Taiji#18]
Hi Kai,

I have a few questions related to the scATAC data analysis using Taiji. 
1) Do you have a more detailed documentation/tutorial on the scATAC analysis?
2) Is it possible to use the output of cellranger-atac in Taiji?
3) Can Taiji also integrate scRNA and scATAC datasets to better calculate the generanks? It seems from the Taiji workflow that Taiji calculates generanks using only scATAC data.
4) Can you please describe how to run scATAC part of Taiji? When I try the example on your tutorial at https://taiji-pipeline.github.io/blog_3_scATAC.html, the run ends in a second with this `[INFO][01-20 01:47] Parts of the program finish successfully` message.

Thanks.

Best,
Ravi

**Comment by kaizhang** [comment]
@ravipatel4 Thanks for using Taiji. I'm actually working on a more detailed tutorial and an updated version of the scATAC pipeline. I plan to update the website and software in hopefully 2 weeks. I will let you know when it is ready.

**Comment by ravipatel4** [comment]
Thanks @kaizhang. Looking forward to that.

**Comment by kaizhang** [comment]
@ravipatel4 Taiji v1.3 was released with new scATAC-seq features. A work-in-progress tutorial can be found here: https://taiji-pipeline.github.io/blog_3_scATAC.html

**Comment by kaizhang** [comment]
It turns out that implementing a fully automated single-cell ATAC-seq pipeline is difficult, as there are many steps need to be manually  tuned in reality, e.g., clustering. Therefore, I'm releasing a software package to facilitate the scATAC-seq analysis: https://github.com/kaizhang/SnapATAC2.
