### ISSUE TITLE
Error running Taiji on ATAC, RNA, and H3K27ac data

### ISSUE THREAD

**Issue by brhodesford** [Taiji-pipeline/Taiji#19]
Hi, I'm currently trying to run Taiji on ATAC, RNA, and H3K27ac data. I've attached the slurm from the job that failed. It gives the following error:

[0m[31m[1m[ERROR][01-26 14:51] [0m[0m[31mOutput_Ranks(34bf..) Failed: Prelude.maximum: empty list
CallStack (from HasCallStack):
  error, called at src/Control/Workflow/Interpreter/Exec.hs:134:37 in SciFlow-0.7.2-Jc8TJcu7aUL61DWlZpDMFY:Control.Workflow.Interpreter.Exec[0m
[0m[31m[1m[ERROR][01-26 14:51] [0m[0m[31mProgram exits with errors[0m

I am having a hard time identifying the problem. Any help would be greatly appreciated.
Thanks,
Rhodes
[slurm-83987.txt](https://github.com/Taiji-pipeline/Taiji/files/5875901/slurm-83987.txt)

**Comment by kaizhang** [comment]
Thanks for reporting this issue. This error occurs when no TFs left after the default filtering process during the HTML creation. This error should not affect the results. In other words, you should get a normal "GeneRanks.tsv" file. However, you won't have an HTML visualization file. I will fix this problem in the upcoming release.

**Comment by brhodesford** [comment]
Thanks for your quick reply!

**Comment by brhodesford** [comment]
Hi, sorry, quick follow up. In the slurm, it doesn't seem like the program is actually considering the H3K27ac data. Has this functionality been removed? I've attached my yaml files in case there is an issue there
[pageRank_config.txt](https://github.com/Taiji-pipeline/Taiji/files/5881650/pageRank_config.txt)
[ALL_input_pageRank.txt](https://github.com/Taiji-pipeline/Taiji/files/5881652/ALL_input_pageRank.txt)

**Comment by kaizhang** [comment]
Yes, this feature has never been officially released as we have not figured out how to best use the H3K27ac data yet. We decide to leave this to the users by allowing users to supply their own peak list.

**Comment by brhodesford** [comment]
Thanks again!
