### ISSUE TITLE
How to run binary file?

### ISSUE THREAD

**Issue by sjm0240111** [Taiji-pipeline/Taiji#2]
Hello, I don't know how to run the binary file, could anyone give a bit hint?
I've failed running it by simply typing `./taiji-Linux-x86_64`, which I think is the binary file.

**Comment by kaizhang** [comment]
@sjm0240111 You need to give the "execute" permission to the file first: `chmod +x taiji-Linux-x86_64`

**Comment by sjm0240111** [comment]
Yes, I did try that, only to find the error `Segmentation fault` : 

`(base) -bash-4.2$ ll | grep taiji
-rwxr-xr-x.  1 exer3 exer3  28180480 Jan 22 04:55 taiji-Linux-x86_64
(base) -bash-4.2$ ./taiji-Linux-x86_64
Segmentation fault`

**Comment by kaizhang** [comment]
Sorry for the late response. What's the version of the taiji and Linux system you were using?

**Comment by sjm0240111** [comment]
Sorry for my late response too! I'm using the latest v1.1.0.I will try to compile the source first.

**Comment by kaizhang** [comment]
You don't need to have root to compile the program. If you can tell me your OS information, I can try to find out why the binary doesn't work on your platform.

**Comment by sjm0240111** [comment]
I'm not sure if this information is right.
`(base) -bash-4.2$ cat /etc/redhat-release`
`CentOS Linux release 7.6.1810 (Core)`
`(base) -bash-4.2$ cat /proc/version`
`Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) `

**Comment by kaizhang** [comment]
It looks like you are using CentOS 7. The binary was compiled on CentOS 7 so that should work unless your system was recently upgraded.

What is the output of `ldd taiji-Linux-x86_64`?

If you want to compile from source, you can follow the instructions here: https://taiji-pipeline.github.io/documentation/install.html.

You don't need the root privilege but the compilation will take a while (1~2 hours).

**Comment by sjm0240111** [comment]
When I run `ldd taiji-Linux-x86_64`
it says ` not a dynamic executable`.
If I compile from source, I had to install stack first, which now requires root privilege, I will try installing it.

**Comment by kaizhang** [comment]
I see. Then you must have downloaded the wrong version. Please use this link to download the correct version: https://github.com/Taiji-pipeline/Taiji/releases/download/v1.1.0/taiji-Linux-x86_64

The binary should be dynamically linked. And the `stack` does not need root. You can download the `stack` binary and just run it.

**Comment by sjm0240111** [comment]
Yeah! I downloaded your correct file, which is bigger than my previous one. I guess last time I met some transfer error. It works pretty well after installing igraph library.
