### ISSUE TITLE
Efficient way to generate new PageRank for slightly altered input file

### ISSUE THREAD

**Issue by cong-003** [Taiji-pipeline/Taiji#20]
Hi Kai,

When I ran Taiji, I came across an error "**Create_Linkage(58c2..) Failed: No gene available for domain assignment!**". I checked the atac peak files and found some samples have no peaks at all. So I deleted those samples from my input file and also tried to let Taiji read my new input by following commands:

```
> taiji delete RNA_Read_Input
> taiji delete ATAC_Read_Input
> taiji run --config human_embryonic_config_hic.yml --select Output_Ranks

```
But it didn't work, so could you help me out please? Do I need to rerun all the previous steps before that? Is there more efficient way to do this?

Thanks a lot!

**Comment by kaizhang** [comment]
This requires an in-depth understanding of the workflow. I will add command-line options to facilitate such operations in future.

**Comment by kaizhang** [comment]
Added a new flag `--delete-smart` which may help in such situations. This new feature will be incorporated in the next stable release. Close this issue for now.

**Comment by cong-003** [comment]
Thanks, Kai!
