### ISSUE TITLE
Error in  Create_linkage step

### ISSUE THREAD

**Issue by sasim7** [Taiji-pipeline/Taiji#21]
Hi Kai,
I got the following error 
Create_Linkage(ea8d..) Failed: No gene available for domain assignment!
CallStack (from HasCallStack):

 I was checking previous posts where this error was encountered when there were no peaks called for some samples.

I checked my run and there were peaks called for all the samples.

What else might have gone wrong?

Thankyou.
Best regards
Sasi

**Comment by kaizhang** [comment]
Could you check the gene annotation file?

**Comment by sasim7** [comment]
Thank you, changing the annotation file helped,just the usual 1 or chr1 format issue.
