### ISSUE TITLE
How to write config file with technical repetitions?

### ISSUE THREAD

**Issue by BW15061999** [Taiji-pipeline/Taiji#25]
Hi,

what should I do if each biological repetiton have two technical repetitions? For example, how should I write `input.yml` file? Is it fine to write 4 rep in one group if I have two biological repetitions with two technical repetitions?

Thank you!

**Comment by kaizhang** [comment]
Hi, it is technically OK to write 4 replications in one group. Currently, there is no way to distinguish technical replicates from biological replicates.

**Comment by BW15061999** [comment]
Thank you!
