### ISSUE TITLE
error while loading shared libraries: libtinfo.so.5

### ISSUE THREAD

**Issue by ebprideaux** [Taiji-pipeline/Taiji#29]
Hi Kai-

I'm getting an error on our new cluster installation when running Taiji-v1.3.0 (pre-built binary for taiji-CentOS-x86_64) and downloaded directly from Github.

When I’m on the head node, I can successfully run Taiji command.  For example:

(taiji) [barton@wangcluster ~]$ taiji
Taiji-v1.3.0

Usage: taiji COMMAND
  Multi-omics bioinformatics analysis pipline. For more details, see:
  https://taiji-pipeline.github.io/

Available options:
  -h,--help                Show this help text

Available commands:
  run                      Run workflow
  delete                   Delete node cache
  show                     Show node cache
  view                     Produce HTML visualization of the workflow
  remote                   Run workflow in the worker mode

When I submit a Taiji job to cluster via the —cloud command on head node, the job hangs and slurm-out files show that the libtinfo.so.5 error comes up.

(taiji) [barton@wangcluster Output]$ taiji run --config $config_fp --cloud

(taiji) [barton@wangcluster Output]$ cat slurm-3920*
/stg2/data2/barton/bin/taiji: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
/stg2/data2/barton/bin/taiji: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

When I’m on an interactive shell on another node, if I run the basi taiji check command, I get the same error.

(base) bash-4.4$ taiji
taiji: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

Do you know what may be causing the issue?

-Barton

**Comment by ebprideaux** [comment]
@kaizhang confirmed this is behavior that occurs in v1.3.0 and v1.2.1.3, but does not occur in v1.2.0.

v1.2.0 is running with no issues.

**Comment by kaizhang** [comment]
The problem probably is that the compute nodes do not have the required library installed. You can ask the system administrator to install the missing library, or copy the library files to your local directory and add them to your path.
