### ISSUE TITLE
Failed: Error in $.replicates.files

### ISSUE THREAD

**Issue by wang-tan** [Taiji-pipeline/Taiji#35]
Hi,
I am trying to run the taiji with my ATAC-seq and RNA-seq, but I got this error:
![image](https://user-images.githubusercontent.com/9820714/218024443-e7553b9d-64b4-496f-95dc-4073a263f4bb.png)
is there something wrong ? Could you help? Thanks a lot!

Best
Tan

**Comment by kaizhang** [comment]
Thanks for using Taiji! Can you upload your input.tsv or input.yml files here?

**Comment by wang-tan** [comment]
Thanks for your reply！I have modified something in my input.tsv, but there were other errors, here is the error and my input file, please help me see what's wrong in it, thank you very much!

![image](https://user-images.githubusercontent.com/9820714/218244788-a8718874-5699-4040-bcbc-fd355d0431e3.png)

[wu_input.txt](https://github.com/Taiji-pipeline/Taiji/files/10712829/wu_input.txt)
