### ISSUE TITLE
Got different node weight when switched the expression files

### ISSUE THREAD

**Issue by avialee** [Taiji-pipeline/Taiji#5]
Hi,

I am running Taiji on our ATAC-seq and RNA-seq data of WT and KO samples. We have two repeats on each type of data. Actually we already got the peak files from ATAC-seq and expression matrix from RNA-seq using our own pipeline. So I fed Taiji with peak files and expression files. However when I switched the 2 repeats of expression files in the input.yml file, I got different values in the nodes.csv. I have no idea how the weight of nodes is calculated. They should be same even the repeat file is switched, right?

Thanks.

**Comment by kaizhang** [comment]
Could you show me the changes you had made in the `input.yml` file?

**Comment by avialee** [comment]
ATAC-seq part is the same, only RNA-seq part is changed:

Before switched:
ATAC-seq:
  - id: WT_atac
    group: WT
    replicates:
      - rep: 1
        files:
          - path: VWT.SI_peaks.narrowPeak
            format: NarrowPeak
  - id: KO_atac
    group: KO
    replicates:
      - rep: 1
        files:
          - path: VKO.SI_peaks.narrowPeak
            format: NarrowPeak

RNA-seq:
  - id: WT_rna
    group: WT
    replicates:
      - rep: 1
        files:
          - path: expression_SI_wt1.tsv
            tags: ['GeneQuant']
      - rep: 2
        files:
          - path: expression_SI_wt2.tsv
            tags: ['GeneQuant']
  - id: KO_rna
    group: KO
    replicates:
      - rep: 1
        files:
          - path: expression_SI_ko1.tsv
            tags: ['GeneQuant']
      - rep: 2
        files:
          - path: expression_SI_ko2.tsv
            tags: ['GeneQuant']

After switched:

ATAC-seq:
  - id: WT_atac
    group: WT
    replicates:
      - rep: 1
        files:
          - path: VWT.SI_peaks.narrowPeak
            format: NarrowPeak
  - id: KO_atac
    group: KO
    replicates:
      - rep: 1
        files:
          - path: VKO.SI_peaks.narrowPeak
            format: NarrowPeak

RNA-seq:
  - id: WT_rna
    group: WT
    replicates:
      - rep: 1
        files:
          - path: expression_SI_wt2.tsv
            tags: ['GeneQuant']
      - rep: 2
        files:
          - path: expression_SI_wt1.tsv
            tags: ['GeneQuant']
  - id: KO_rna
    group: KO
    replicates:
      - rep: 1
        files:
          - path: expression_SI_ko2.tsv
            tags: ['GeneQuant']
      - rep: 2
        files:
          - path: expression_SI_ko1.tsv
            tags: ['GeneQuant']

**Comment by kaizhang** [comment]
There shouldn't be any differences. In the `RNASeq` directory, there is a file named `expression_profile`. Please check whether the file stays the same between the two runs.

**Comment by avialee** [comment]
Here are the fist a few lines in expression_profile.tsv, it is also switched:

before switched:
	WT	WT	KO	KO
Ubl5	565.0413975	670.3987042	558.0231156	736.6467091
Gm38348	0.0	0.0	2.783157684	0.0
Ttc32	77.0089261	73.81095833	73.75367862	89.25241697

after switched:
	WT	WT	KO	KO
Ubl5	670.3987042	565.0413975	736.6467091	558.0231156
Gm38348	0.0	0.0	0.0	2.783157684
Ttc32	73.81095833	77.0089261	89.25241697	73.75367862

**Comment by kaizhang** [comment]
I see. This is probably a bug introduced in v1.1.0. I will fix it this weekend.

**Comment by avialee** [comment]
Thanks!

**Comment by kaizhang** [comment]
Fixed in [v1.2.1](https://github.com/Taiji-pipeline/Taiji/releases/tag/v1.2.1).
