### ISSUE TITLE
Result confirm

### ISSUE THREAD

**Issue by ShikanZ** [Taiji-pipeline/Taiji#6]
Hi Kai,

I want to confirm some Taiji results. 

Is the GeneRanks.tsv Pagerank score? 
How does the Heatmap generated? In the Generank tsv, I have about 600 genes, but in the Heatmap, It only showed few. Does it only plot the most variable genes?

Thanks,

Shikan

**Comment by kaizhang** [comment]
Yes, the heatmap only plots the most variable genes. It first filters the genes by p-value and then by variability.
